### ISSUE TITLE
WebSocket and Dash Chartjs

### ISSUE THREAD

**Issue by GustavoBrazilBIConsultant** [zenalytiks/dash-chartjs#2]
react-dom@16.v2_14_1m1701533714.14.0.min.js:125 TypeError: Cannot read properties of undefined (reading 'length')
    at La.generateLabels (dash_chartjs.v0_0_8m1701533419.min.js:2:345685)
    at p (dash_chartjs.v0_0_8m1701533419.min.js:2:283635)
    at La.buildLabels (dash_chartjs.v0_0_8m1701533419.min.js:2:432388)
    at La.update (dash_chartjs.v0_0_8m1701533419.min.js:2:432117)
    at Ci (dash_chartjs.v0_0_8m1701533419.min.js:2:384136)
    at Object.update (dash_chartjs.v0_0_8m1701533419.min.js:2:386490)
    at ws._updateLayout (dash_chartjs.v0_0_8m1701533419.min.js:2:403037)
    at ws.update (dash_chartjs.v0_0_8m1701533419.min.js:2:401877)
    at dash_chartjs.v0_0_8m1701533419.min.js:2:480426
    at Bh (react-dom@16.v2_14_1m1701533714.14.0.min.js:126:456)
    
    In the console log , i received that error

**Comment by zenalytiks** [comment]
> [react-dom@16.v2_14_1m1701533714.14.0.min.js](mailto:react-dom@16.v2_14_1m1701533714.14.0.min.js):125 TypeError: Cannot read properties of undefined (reading 'length') at La.generateLabels (dash_chartjs.v0_0_8m1701533419.min.js:2:345685) at p (dash_chartjs.v0_0_8m1701533419.min.js:2:283635) at La.buildLabels (dash_chartjs.v0_0_8m1701533419.min.js:2:432388) at La.update (dash_chartjs.v0_0_8m1701533419.min.js:2:432117) at Ci (dash_chartjs.v0_0_8m1701533419.min.js:2:384136) at Object.update (dash_chartjs.v0_0_8m1701533419.min.js:2:386490) at ws._updateLayout (dash_chartjs.v0_0_8m1701533419.min.js:2:403037) at ws.update (dash_chartjs.v0_0_8m1701533419.min.js:2:401877) at dash_chartjs.v0_0_8m1701533419.min.js:2:480426 at Bh ([react-dom@16.v2_14_1m1701533714.14.0.min.js](mailto:react-dom@16.v2_14_1m1701533714.14.0.min.js):126:456)
> 
> ```
> In the console log , i received that error 
> ```

It'd be great if you could share a minimal code snippet to reproduce this error.

**Comment by GustavoBrazilBIConsultant** [comment]
my dashboard

layout = html.Div([
    WebSocket(id="ws"),
    dcc.Store(id='store-graph1'),
    dcc.Interval(id='interval-component', interval=1000, n_intervals=0),  # Update every 1 second
    html.Div([
        html.Img(src='assets\logo_v.png', style={'width': '60px','height': '45px','margin-left': '0px', 'margin-top': '6px', 'border-style': 'none'}, className="col-1 card text-black rounded-0"),
        html.H1("Dashboard", className="col-9 card text-black rounded-0", style={'border-style': 'none'})
    ], className="row mx-2 justify-content-center"),
    html.Div([
        html.Div([
            dbc.Container([
                dbc.Row([
                    html.H2("Vendas por Serviço")
                ]),
                dbc.Row([
                    dbc.Col(
                        html.Div([
                        ChartJs(
                            id='graph_servico',
                            type='pie',
                            data= 
                                {
                                        "labels": x,
                                        "datasets": [
                                            {
                                                "data": y,
                                                "backgroundColor": "#57C5C8",
                                                "borderWidth": 4,
                                                "hoverBorderColor": "white",
                                                "label": "Vendas"
                                            }
                                        ]
                                    },
                            options={
                                "cutoutPercentage": 20,
                                "legend": {"display": True},
                                "layout": {"padding": 0},
                                "scale": {
                                    "ticks": {"max": 450, "maxTicksLimit": 1, "display": False},
                                    "angleLines": {"display": False},
                                    "pointLabels": {"display": False}
                                },
                                "plugins": {
                                    "datalabels": {"display": True},
                                    "legend": {"display": False}
                                }
                            },
                            style={
                                'position': 'relative',
                                'width': '80%',
                                'height': '0',
                                'margin-top': '0px'
                            }
                        ),
                         # Inclua a tag <script> para o seu arquivo JavaScript
                         html.Script(src='/static/app.js')
                        ]),
                        width=7
                    ),
                    dbc.Col(
                        html.H1('', id='vendas_text', style={'font-size': '25px'}),
                        width=5,
                        align='center',
                        className='align-self-center'
                    )
                ], className='mb-4 align-items-center')
            ]),
        ], className="col-3 card bg-secondary text-white rounded m-3", style={'height': '300px', 'width': '555px'}),
        html.Div([
            html.Div([
                html.H2("Forma de Pagamento"),
                html.P("Conteúdo do Card 2"),
            ]),
        ], className="col-3 card bg-light rounded m-3", style={'height': '300px', 'width': '555px'}),
        html.Div([
            html.Div([
                html.H2("Card 3"),
                html.P("Conteúdo do Card 3"),
            ]),
        ], className="col-3 card bg-light rounded m-3", style={'height': '300px', 'width': '555px'}),
    ], className="row mx-2 justify-content-center"),
    html.Div([
        html.Div([
            html.H2("Card 4 (Branco)"),
            html.P("Conteúdo do Card 4"),
        ], className="col-9 card bg-light rounded m-2", style={'height': '400px', 'width': '1730px'}),
    ], className="row justify-content-center")
])
app.clientside_callback(
    """
function(msg) {
    if (msg) {
        const data = JSON.parse(msg.data);
        const x = data.x; // Aqui você obtém o array correspondente a 'x'
        const y = data.y; // Aqui você obtém o array correspondente a 'y'

        // Crie a estrutura de dados conforme necessário para o gráfico
        const graphData = {
            labels: x,
            datasets: [
                 {
                 data: y,
                 backgroundColor: "#57C5C8",
                 borderWidth: 4,
                 hoverBorderColor: "white",
                 label: "Vendas",
                 },
            ];
        };
        
        // Exiba os dados no console
        console.log('Graph Data:', graphData);

        return {
            graphData,
        };
    } else {
        return {};
    }
}""",
    Output("graph_servico", "data"),
    [Input("ws", "message")],
)



in another .py has te @app.server.websocket using a variable given by a callback

@app.callback(
    [
        Output('store-graph1', 'data'),
        Output('Select_OS', 'options'),
        Output('mensagem-sucesso-entrada', 'children'),
        Output('select-cliente-entrada', 'value'),
        Output('select-Serviço', 'value'),
        Output('input-Valor', 'value'),
        Output('select-Forma', 'value'),
        Output('input-data-entrada', 'value'),
    ],
    [Input('botao-cadastro-entrada', 'n_clicks')],
    [
        State('select-cliente-entrada', 'value'),
        State('select-Serviço', 'value'),
        State('input-Valor', 'value'),
        State('select-Forma', 'value'),
        State('input-data-entrada', 'value'),
        State('card-id-client', 'children')  # Adicione o novo State aqui
    ]
)
def register_data(n_clicks, cliente, servico, valor, forma, data, cliente_id):
    if n_clicks is None:
        raise PreventUpdate 
    if cliente is not None and servico is not None and valor is not None and forma is not None and data is not None and valor > 0:
        # Utilize o ID do cliente fornecido pelo callback anterior
        if cliente_id:
            # Converter a data para o formato desejado
            data_formatada = datetime.strptime(data, '%Y-%m-%d').date()

            # Criar uma nova entrada na tabela fFaturamento
            new_entry = fFaturamento(
                id_cliente=cliente_id,
                Nome=cliente,
                Serviço=servico,
                Valor=valor,
                Pagamento=forma,
                Data=data_formatada  # Usar a data formatada
            )

            # Adicionar a nova entrada à sessão e fazer commit no banco de dados
            session.add(new_entry)
            session.commit()

            global agrupado_por_servico

            # Fechar a sessão após o uso
            session.close()
            
            nova_linha = pd.DataFrame([{'Serviço': servico, 'Valor': valor}])

            agrupado_por_servico = pd.concat([agrupado_por_servico, nova_linha], ignore_index=True)

            # Agrupar por serviço e calcular a soma dos valores
            agrupado_por_servico = agrupado_por_servico.groupby('Serviço')['Valor'].sum().reset_index()

            
            # Converta o DataFrame para uma lista de dicionários
            dict_agrupado_por_servico = agrupado_por_servico.to_dict(orient='records')
            # Limpar os campos
            return (
                dict_agrupado_por_servico,
                os_lista,
                html.Div([
                    html.P(f"Entrada cadastrada com sucesso! Dados registrados para o cliente {cliente}", style={'color': 'green', 'font-weight': 'bold', 'font-size': '20px'})
                ]),
                None,  # Limpar 'select-cliente-entrada'
                None,  # Limpar 'select-Serviço'
                None,  # Limpar 'input-Valor'
                None,  # Limpar 'select-Forma'
                datetime.now().date(),  # Limpar 'input-data-entrada'
            )
    else:
        return dict_agrupado_por_servico, os_lista, html.Div([html.P(f"Preencha corretamente!",style={'color': 'red', 'font-weight': 'bold', 'font-size': '20px'})]), None, None, None, None, None


@app.server.websocket("/ws")
async def ws():
    while True:
        global agrupado_por_servico
        x_values = agrupado_por_servico['Serviço'].tolist()
        y_values = agrupado_por_servico['Valor'].tolist()
        output = json.dumps({'x': x_values, 'y': y_values})
        
        await websocket.send(output)
        await asyncio.sleep(1)

**Comment by GustavoBrazilBIConsultant** [comment]
wait, the serverside of dash_chartsjs is an... img?
![image](https://github.com/zenalytiks/dash-chartjs/assets/151473349/0ef55ff1-e142-4157-9d4b-679b9e7785e0)

so, how i can make updates on serverside to all clientes?

**Comment by zenalytiks** [comment]
Here's a small example of how you can use WebSocket and dash-chartjs together:

**websocket.py:**
```python
import asyncio
import json
import random
from quart import websocket, Quart

app = Quart(__name__)

@app.websocket("/random_data")
async def random_data():
    while True:
        output = json.dumps([random.random() for _ in range(10)])
        await websocket.send(output)
        await asyncio.sleep(1)

if __name__ == "__main__":
    app.run(port=5000)
```

**app.py**
```python
from dash_extensions import WebSocket
from dash_extensions.enrich import html, Output, Input, DashProxy
from dash_chartjs import ChartJs

# Client-side function (for performance) that updates the graph.
update_graph = """function(msg) {
    if(!msg){return {};}  // no data, just return
    const data = JSON.parse(msg.data);  // read the data
    return {
        datasets: [{
            label: 'Visitors to Georgia',
            data: data,
            fill: false,
            borderColor: 'rgb(75, 192, 192)',
            tension: 0.1
        }]
    };  // plot the data
}
"""
# Create small example app.
app = DashProxy(__name__)
options = {
    'scales': {
        'x': {
            'type':'category',
            'labels': ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October']
        }
    },
    'plugins':{
        'zoom':{
            'zoom':{
                'wheel':{
                    'enabled': True
                },
            'mode':'xy'
            }
        }
    } 
}
app.layout = html.Div([
    WebSocket(id="ws", url="ws://127.0.0.1:5000/random_data"),
    ChartJs(id='graph',type='line',options=options)
])
app.clientside_callback(update_graph, Output("graph", "data"), Input("ws", "message"))

if __name__ == "__main__":
    app.run_server(debug=True)
```
